//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeEditor.ResourceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResourceService.IResourceService", CallbackContract=typeof(TreeEditor.ResourceService.IResourceServiceCallback))]
    public interface IResourceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/Login", ReplyAction="http://tempuri.org/IResourceService/LoginResponse")]
        bool Login(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/Login", ReplyAction="http://tempuri.org/IResourceService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/TryLock", ReplyAction="http://tempuri.org/IResourceService/TryLockResponse")]
        bool TryLock(int id, Model.Data.ItemType itemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/TryLock", ReplyAction="http://tempuri.org/IResourceService/TryLockResponse")]
        System.Threading.Tasks.Task<bool> TryLockAsync(int id, Model.Data.ItemType itemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetSingleItem", ReplyAction="http://tempuri.org/IResourceService/GetSingleItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Data.CollectionPoint))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Data.Client))]
        Model.Data.Item GetSingleItem(int id, Model.Data.ItemType itemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetSingleItem", ReplyAction="http://tempuri.org/IResourceService/GetSingleItemResponse")]
        System.Threading.Tasks.Task<Model.Data.Item> GetSingleItemAsync(int id, Model.Data.ItemType itemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetAllItems", ReplyAction="http://tempuri.org/IResourceService/GetAllItemsResponse")]
        System.Collections.Generic.List<Model.Data.Item> GetAllItems(Model.Data.ItemType itemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetAllItems", ReplyAction="http://tempuri.org/IResourceService/GetAllItemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Model.Data.Item>> GetAllItemsAsync(Model.Data.ItemType itemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/UpdateItem", ReplyAction="http://tempuri.org/IResourceService/UpdateItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Data.CollectionPoint))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Data.Client))]
        bool UpdateItem(Model.Data.Item theItem, Model.Data.ItemType itemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/UpdateItem", ReplyAction="http://tempuri.org/IResourceService/UpdateItemResponse")]
        System.Threading.Tasks.Task<bool> UpdateItemAsync(Model.Data.Item theItem, Model.Data.ItemType itemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/DeleteItem", ReplyAction="http://tempuri.org/IResourceService/DeleteItemResponse")]
        bool DeleteItem(int id, Model.Data.ItemType itemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/DeleteItem", ReplyAction="http://tempuri.org/IResourceService/DeleteItemResponse")]
        System.Threading.Tasks.Task<bool> DeleteItemAsync(int id, Model.Data.ItemType itemType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourceServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IResourceService/LockedNotification")]
        void LockedNotification(string owner, Model.Lock.LockBatch batch);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourceServiceChannel : TreeEditor.ResourceService.IResourceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceServiceClient : System.ServiceModel.DuplexClientBase<TreeEditor.ResourceService.IResourceService>, TreeEditor.ResourceService.IResourceService {
        
        public ResourceServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ResourceServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ResourceServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool Login(string loginName) {
            return base.Channel.Login(loginName);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string loginName) {
            return base.Channel.LoginAsync(loginName);
        }
        
        public bool TryLock(int id, Model.Data.ItemType itemType) {
            return base.Channel.TryLock(id, itemType);
        }
        
        public System.Threading.Tasks.Task<bool> TryLockAsync(int id, Model.Data.ItemType itemType) {
            return base.Channel.TryLockAsync(id, itemType);
        }
        
        public Model.Data.Item GetSingleItem(int id, Model.Data.ItemType itemType) {
            return base.Channel.GetSingleItem(id, itemType);
        }
        
        public System.Threading.Tasks.Task<Model.Data.Item> GetSingleItemAsync(int id, Model.Data.ItemType itemType) {
            return base.Channel.GetSingleItemAsync(id, itemType);
        }
        
        public System.Collections.Generic.List<Model.Data.Item> GetAllItems(Model.Data.ItemType itemType) {
            return base.Channel.GetAllItems(itemType);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Model.Data.Item>> GetAllItemsAsync(Model.Data.ItemType itemType) {
            return base.Channel.GetAllItemsAsync(itemType);
        }
        
        public bool UpdateItem(Model.Data.Item theItem, Model.Data.ItemType itemType) {
            return base.Channel.UpdateItem(theItem, itemType);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateItemAsync(Model.Data.Item theItem, Model.Data.ItemType itemType) {
            return base.Channel.UpdateItemAsync(theItem, itemType);
        }
        
        public bool DeleteItem(int id, Model.Data.ItemType itemType) {
            return base.Channel.DeleteItem(id, itemType);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteItemAsync(int id, Model.Data.ItemType itemType) {
            return base.Channel.DeleteItemAsync(id, itemType);
        }
    }
}
